### PR TITLE
MySQL Metadata changes

### PR DESCRIPTION
**Pull request by MShark67**
I tried to break these up into separate commits to make it easier to pick and choose if needed.  The last commit changes all of the metadata result sets to return database in the schema column instead of the catalog column, so this is a breaking change.

### CODE REVIEW

**Comment by marsupilami79** [comment]
Hello Mark,

I didn't apply 4f72bad because of our ongoing discussion on the forums. I applied the other patches though. There seems to be a problem related to your changes. There is a test that fails since I applied your patches. See:
https://www.iks.ag/jenkins/view/Zeos%20Trunk/job/ZTestAll%20Trunk%20with%20Delphi%202010/56/

Do you have a chance to check this?

**Comment by MShark67** [comment]
I spent about 3 hours this morning trying to figure out why that test would fail, but I'm completely stumped.  Perhaps my understanding of things is just flat out wrong.   This seems to relate to my NormalizePatternCase fix, which I was fairly confident about (and I've been using it all my testing here.)  I don't see how my change would even affect PostgreSQL as it uses a lowercase dictionary (except for quoted idents.)  My change should only affect a protocol that returns true for "storesmixedcaseidentifiers" which PostgreSQL does not.  Is it possible to get the actual values during that particular test?   I *think* that the value of ConnectionConfig.Database should be 'zeoslib', at least according to my search through the test files.

**Comment by MShark67** [comment]
Hey, could you let me know what individual test you're talking about?  With no prior knowledge of the test reports I have no idea which one of those 48 failures is the specific one.  If it's /postgresql95.dbc/TZTestPostgreSqlMetadataCase/TestGetCatalogs/ then I'm not sure how my changes relate to it.  Thanks.

**Comment by marsupilami79** [comment]
Hello Mark,

I am sorrry for my late reply. Yes - I meant TestGetCatalogs for PostgreSQL. I will have a look into this later on. For now I am closing this pull request.
Best regards,

Jan

**Pull request closed without merging**
