### PR TITLE
ZStoredProc "Cannot retrieve resultset" with multiple schemas / catal…

### PR DESCRIPTION
**Pull request by aehimself**
…ogs fix

See https://zeoslib.sourceforge.io/viewtopic.php?f=50&t=132822

### CODE REVIEW

**Comment by marsupilami79** [comment]
I applied your patch and wait if the test suites show any problem (which they most probably will not). Could you try to write up a small test case for ZTestBugCompOracle.pas? So we will see if the problem is reintroduced for some reason?

**Comment by aehimself** [comment]
The Delphi part is easy. Create a connection, set a schema, connect TZStoredProc and execute. Setting up the database is more complicated. Have two schemas, make sure the user can access both. Create the same stored procedure in both of the schemas.
No need to check for anything as it should throw an exception without the patch, failing the test automatically.

So effectively...

```
Var
 conn: TZConnection;
 proc: TZStoredProc;
Begin
 conn := TZConnection.Create(nil);
 Try
  conn.Database := 'something';
  conn.User := 'something';
  conn.Password := 'something';
  conn.Catalog := 'Schema1';
  conn.Connect;
  
  proc := TZStoredProc.Create(nil);
  Try
   proc.Connection := conn;
   proc.StoredProcName := 'StoredProcedure';
   proc.ExecProc;
  Finally
   proc.Free;
  End;
 Finally
  conn.Free;
 End;
End;
```

Unfortunately I can not help with the Oracle part as I never declared any stored procedures and therefore I don't know how to :(

**Comment by marsupilami79** [comment]
> Unfortunately I can not help with the Oracle part as I never declared any stored procedures and therefore I don't know how to :(

I think we do have generic tests for stored procdures. Maybe there is an example on how to create a stored procedure in the create scripts of the test suite in the database directory? I can't do this myself because I am still tight on time. :(

**Comment by aehimself** [comment]
There's no need for a separate test, there is one included already:

```
procedure TZTestOracleStoredProcedure.ORA_Test_abtest;
begin
  abtest();
end;

procedure TZTestOracleStoredProcedure.abtest(prefix: string);
begin
  StoredProc.StoredProcName := prefix+'ABTEST';
```

If we make sure that the connection of this StoredProc object has a Catalog property AND the user has access to one more schema with the same (ABTEST) stored procedure the test case is implemented :)

**Pull request closed without merging**
