### PR TITLE
Possible fix for Oracle 1406 errors with UTF16.

### PR DESCRIPTION
**Pull request by MShark67**
This needs testing as well as a check that the code meets Zeoslib coding standards.

-Mark

### CODE REVIEW

**Comment by aehimself** [comment]
```
    Data: TBytes;
    DataIndicators:  TArray<sb2>;
    DataLengths:    TArray<ub2>;
```

These won't compile on older Delphi versions for sure. You can leave it as it is for now and once merged I can fix it on my dev machine and issue an other PR with the adjustment.

**Comment by aehimself** [comment]
As it turns out ZCompatibility defines TBytes:
```
  {$IF NOT DECLARED(TBytes)}
  TBytes = TByteDynArray;
  {$IFEND}
```
So the only things which have to be changed are
```
    DataIndicators:  Array Of sb2; // TArray<sb2>;
    DataLengths:    Array Of ub2; // TArray<ub2>;
```
and Zeos compiles nicely on Delphi 7.

**Comment by MShark67** [comment]
Thanks!  I made that fix.

**Comment by marsupilami79** [comment]
I added the patch to SVN. It shoould show up here tomorrow. Thank you and best regards,

Jan

**Pull request closed without merging**
