### PR TITLE
Compatibility issues with Delphi7/XE fixed and allow overwrite of get/setURL TZURL

### PR DESCRIPTION
**Pull request by ThomasKalten**
src/dbc/ZDbcBeginnerStatement.pas
- Delphi7 without DefaultCodePage - Compilerswitch was not applied

src/dbc/ZDbcFirebirdInterbase.pas
- Delphi does not accept PRawByteString as Var-Parameter

src/dbc/ZDbcIntfs.pas
- allow overwrite of URL in TZURL - derived class used with more special params in the url

 src/dbc/ZDbcOracleResultSet.pas
- FColumns of type Array - "FColumns^.Variables[C]" not accepted by Delphi-Compiler

### CODE REVIEW

**Comment by aehimself** [comment]
Are you talking about compile or runtime incompatibilities? I'm asking because Zeos compiles just fine under Delphi 7, I checked it last week in a [different pull request](https://github.com/marsupilami79/zeoslib/pull/88).

**Comment by aehimself** [comment]
Just checked again, after Michael's commits. At it's current state of the repository (latest commit a9acc1f8838d039b808af672c4effd82eee2ff9d) Zeos package compiles and installs happily on Delphi 7; only a few deprecated warnings are present.
So my question still stands - what kind of incompatibility did you attempt to fix?

**Comment by ThomasKalten** [comment]
I discribed the problems that occured in the patch  message.
If the compiler says,  it does not compile, it does not compile.
I will try a fresh checkout.

Viele Grüße 


Am 17. Februar 2024 21:34:44 MEZ schrieb aehimself ***@***.***>:

**Comment by marsupilami79** [comment]
Hallo Thomas,

--> German Version
ich habe eben auf meiner Testmaschine Delphi 7 Professional (Build 4453) angeworfen. Vorher habe ich meine SVN-Kopie von Zeos 8 vollständig bereinigt. Danach habe ich die ZeosDbo.bpg in packages/delphi7 geöffnet und die Pakete von oben nach unten kompiliert (core, parsesql, plain, dbc, component, componendesign). Alle Pakete konnten kompiliert werden.

Deine Fehlermeldungen lassen mich vermuten, dass bei dir möglierweise noch irgendwo alte DCUs rumliegen. Möglicherweise von Zeos 7.2? Bitte bereinige deinen Rechner. Lösche alle DCU-, DCP-, und BPL-Dateien, die irgendwas mit Zeos zu tun haben (könnten).

--> English Version
i opened my Delphi 7 Professional (Build 4453) on my test machine. Before doing so, I cleaned up my SVN copy of Zeos 8 completely. After doing that, I opened the ZeosDbo.bpg in packages/delphi7 and compiled the packages from top to bottom (core, parsesql, plain, dbc, component, componentdesign). Al packages could be compiled on my machine.

Because of your error messages I guess that there are some olöd DCUs somewhere on your machine. Maybe from zeos 7.2? Please clean up your computer. Remove all DCU-, DCP-, and BPL-Files that (may) have to do something with Zeos.

Best regards,

Jan

**Comment by ThomasKalten** [comment]
I found the difference:
In my project I use the compiler switch MORMOT2.
In my project I don't use the bpls.

Then in the file  ZDbcFirebirdInterbase.pas i.e. the type PRawByteString is used from unit mormot.core.base.pas.
With out the switch this clauses in ZDbcFirebirdInterbase.pas in line 4554 makes the difference:

{$IF not declared(PRawByteString)}
type
  PRawByteString = ^RawByteString;
{$IFEND}

So the compiler does not match these both types.
I cannot decide at the moment, how to resolve this.
The best would be, I think, to declare PRawByteString already in the unit ZCompability
where also RawByteString is declared.
Then the correct reference could achieved with the ZCompability  prefix to PRawByteString;

My other points I did not inspect further now.

Viele Grüße
Thomas Kaltenbrunner

**Comment by ThomasKalten** [comment]
Bug in src/dbc/ZDbcOracleResultSet.pas, line 483:

With compiler switch MORMOT2 also the compiler switch WITH_COLUMNS_TO_JSON is active.
The bug is in the code, which is only active with this switch.

The last one in ZDbcBeginnerStatement.pas I will inspect later, when I have solved a little D7 problem after trying to apply the D7 patches.

**Pull request closed without merging**
