### PR TITLE
Fix for TZParam.Value type?

### PR DESCRIPTION
**Pull request by aehimself**
See https://zeoslib.sourceforge.io/viewtopic.php?p=170902#p170902

### CODE REVIEW

**Comment by marsupilami79** [comment]
I merged this into Zeos and updated GIT. Thank you :)

**Comment by marsupilami79** [comment]
This change makes component.TZTestExecSQLCase.TestKeepParams fail. Is this a design flaw in the test or in the change?

**Comment by aehimself** [comment]
@marsupilami79 I guess it's the test. Since .Value now correctly (?) sets the data type of the parameter,

```
  Query.Params[0].DataType := ftInteger;
  Query.Params[0].Value := TEST_ROW_ID;
```

will now set the DataType to ftWord. Switch those two and the test will pass:

```
  Query.Params[0].Value := TEST_ROW_ID;
  Query.Params[0].DataType := ftInteger;
```

Should I make a pull request of it?

**Comment by marsupilami79** [comment]
I suggest to wait for the discussion with Egonhugeist ;)

**Pull request closed without merging**
