### PR TITLE
Oracle loblocator changes.

### PR DESCRIPTION
**Pull request by MShark67**
Fixes to UTF8 lob reading and writing.  Threefold performance improvement for "None" and "OnAccess" cachelobmodes.

### CODE REVIEW

**Comment by MShark67** [comment]
Note that I've fixed the TZOracleLobStream64.ReadPoll function.  The existing code failed due to not properly handling the very finicky buffer sizes related to the LobPrefetch size (which defaults to 8k in Zeos.)  However I've replaced that call with a non-polling version named ReadFull which is simpler and safer.  I've left both versions in just in case there's a need.

**Comment by marsupilami79** [comment]
Hello Mark,

again I am sorry for the delay. I wanted to have a running Oracle installation and automated tests before I apply the patch. The patch is applied and now I only will wait for the test results before I close the PR. THe changes should sow up on github by tomorrow.

Thank you and best regards,

Jan

**Comment by marsupilami79** [comment]
Hello Mark,

so - Jenkins has done its job and we have test results for Oracle 21 and Oracle 11. Some of the tests fail now:
[TZTestDbcOracleCase.TestLongObjects](https://www.iks.ag/jenkins/view/Zeos%208.0/job/ZTestAll%207.3%20with%20Delphi%20XE%202%20X86%20Windows/lastCompletedBuild/testReport/oracle21.dbc/TZTestDbcOracleCase/TestLongObjects/)
[TZTestDbcOracleCase.TestLargeBlob](https://www.iks.ag/jenkins/view/Zeos%208.0/job/ZTestAll%207.3%20with%20Delphi%20XE%202%20X86%20Windows/lastCompletedBuild/testReport/oracle21.dbc/TZTestDbcOracleCase/TestLargeBlob/)
These tests fail for Oracle 21 as well as Oracle 11.

[TZGenericTestDataSet.Test_LobCacheMode](https://www.iks.ag/jenkins/view/Zeos%208.0/job/ZTestAll%207.3%20with%20Delphi%20XE%202%20X86%20Windows/lastCompletedBuild/testReport/oracle21.component/TZGenericTestDataSet/Test_LobCacheMode/)
This test fails for Oracle 21 only...

Is there any chance for you to look into that?

**Comment by MShark67** [comment]
Apologies!  I don't have the test environment setup and so I've been trying to replicate those tests in new code.  I only have Oracle 19 as a testbed.  I haven't been able to replicate those errors on my end.  The "TestLongObjects" test is very simple, so if it's failing it must be something different about the environment or Zeos settings between myself and the tests.

The tests that fail with "OCILobIsTemporary" are interesting.  I added Temporary Lob Freeing in TZbstractOracleBlob.FreeOCIResources as the older code didn't appear to ever free temporary lobs.  We could try just removing it to see if that clears the tests and then if the error message changed to "OCIDescriptorFree" it would show that the issue is with the loblocated at that point.

However, if you don't want to mess with that, I don't have any better idea than to back out the changes.  And I apologize for that.  I really did test extensively here, but obviously I'm missing something.

**Comment by MShark67** [comment]
After further thought and a bunch of testing here are my thoughts:

We can't use this pull request as is.   It will have problems with blob lifetime if an uncached recordset (unrelated to lobcachemode btw) is used (and not just the issues you found, there will be an issue with the same blob requested multiple times in different scopes.)  I don't believe the technique I used (blobs managing their own loblocators) can be made to work.

I have another pull request which will give the same performance boost for cached recordsets and should avoid the issues above, but it will have the side effect of using more loblocators and associated memory for uncached resultsets.  In my case, the performance improvement will be worth it, but uncached result sets will be affected unless it's possible to tell from inside TZOracleAbstractResultSet that is being used by a cached result set (I'm not sure that's possible.)

Again, sorry about this.  I've now been able to setup the testing environment and so will try to avoid this kind of thing in the future.  I've had no luck recreating the LobCacheMode error at all, but hopefully backing out this pull request will fix it too.

-Mark

**Comment by MShark67** [comment]
Update... I may have solved it.  Testing now.

**Comment by MShark67** [comment]
I've pushed a new pull request with the fixes.  A lot of the above can be ignored now as the cumulative changes should give the performance improvements without affecting forward-only uncached result sets.  I did not do anything related to Test_LobCacheMode as I can't get it to fail on my system.  Any additional info on that one is appreciated.

**Comment by marsupilami79** [comment]
I merged this into SVN. Sorry again for the delay.

**Pull request closed without merging**
