### PR TITLE
Timestamp format

### PR DESCRIPTION
**Pull request by MShark67**
This fixes the current fractional trimming inconsistency between simple (no am/pm) and non-simple time formats.

### CODE REVIEW

**Comment by MShark67** [comment]
I'm still learning git and github and I'm not sure why this pull request includes all these commits.  I'm just trying to push the final commit that only affects ZAbstractRODataset.  I'm going to reopen this but I hope it's not a disaster...  Thanks!

**Comment by marsupilami79** [comment]
I didn't have time to integrate this yet. Unfortunatley I am tight on time currently. Do you still want ebb390c to be integrated into Zeos? Best regards,

Jan

**Comment by MShark67** [comment]
No worries!  If you could integrate   <https://github.com/marsupilami79/zeoslib/commit/ebb390cc8dc624d9739eaa2232af775583b83b62> ebb390c whenever you get a chance it is appreciated, but there is no rush.  Thanks.

 

-Mark

**Comment by marsupilami79** [comment]
I applied the patch to trunk / master. I will wait for the outcome of the test suite before I merge it to Zeos 8.0.
Best regards, Jan

**Pull request closed without merging**
